final dhanmondiHospitalMapList = [
  {
    "name": "Ibn Sina hospital",
    "type": "Hospital in Dhaka",
    "rating": 4.0,
    "isfavourite": false,
    "image": "assets/host.png",
    "phone": "01823-039800",
    "hours": "Open 24 Hours",
    "address": "H.No 48,Road No. 9/A,Dhanmondi,Dhaka-1209",
    "description":
        "The Ibn Sina Trust started its journey in June 1980 with a noble vision “To serve the humanity”. Our laboratory has 3 Tesla MRI, 128 slice CT scan machine and other latest imaging and laboratory machineries. It won’t be excess to mention that we have introduced these machines well ahead of other countries of South Asia. World famous Siemens-Germany, General Electronic-USA, Olympus Japan, Kiazon Japan, Nihonkoden Japan, and Fuji Japan are our proud suppliers.",
  },
  {
    "name": "Central Hospital Ltd",
    "type": "General Hospital in Dhaka",
    "rating": 4.0,
    "isfavourite": false,
    "image": "assets/host.png",
    "phone": "02-9660015",
    "hours": "Open 24 Hours",
    "address": "House #2, Road No. 5, Dhaka-1205",
    "description":
        "We are committed to provide you with the highest standards of care at Central Hospital Ltd.Here, patients receive genuine care and comfort from experienced staff in pleasant, comfortable surroundings. The Group’s strength includes its commitment to Quality, leasing edge technology and infrastructure for doctor’s and staff’s continuing professional development.",
  },
  {
    "name": "Women's And Children's General Hospital",
    "type": "Hospital in Dhaka",
    "rating": 4.0,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "02-9115458",
    "hours": "Open 24 Hours",
    "address":
        "House-48/6, Road-9/A, Satmasjid Road, Dhanmondi R/A, Dhaka 1209",
    "description": "",
  },
  {
    "name": "Crescent Gastroliver & General Hospital",
    "type": "General Hospital in Dhaka",
    "rating": 3.0,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "02-9671571",
    "hours": "Open 24 Hours",
    "address": "25/i, Green Road [Eastern end of Dhanmondi Road #7, Dhaka 1205",
    "description":
        "Crescent Gastroliver & General Hospital was established in December 2000. This is a 41 bedded hitech superspeciality hospital with all allied subspecialities. ",
  },
  {
    "name": "Farabi General Hospital",
    "type": "General Hospital in Dhaka",
    "rating": 3.5,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "02-9140442",
    "hours": "Everyday(8 AM-12 PM)",
    "address": "House No.8, Road No.14, Dhaka-1209",
    "description":
        "This is a private hospital. Hospitals have a good number of renown doctors. We have our own ambulance and other hospital services. Wheelchair accessibility is available.",
  },
  {
    "name": "Bangladesh ENT Hospital",
    "type": "Specialized Hospital in Dhaka",
    "rating": 4.0,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "01717 250667",
    "hours": "Open 24 Hours",
    "address": "4/1/A, Sobhanbag, Mirpur Road, Dhaka, Dhaka 1207",
    "description":
        "This is the largest ENT and Head Neck Surgery Hospital in Private sector in Bangladesh. It is Situated at the heart of the City in a well communicated area.It is a  30 bed fully equipped modern  , complete hospital dedicated for the treatment of  Ear Nose Throat and Head Neck diseases including cancer treatment  in Bangladesh with One stop service following  International standard.",
  },
  {
    "name": "Shahabuddin Medical College Hospital",
    "type": "Specialized Hospital in Dhaka",
    "rating": 4.0,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "01713-033375",
    "hours": "Open 24 Hours",
    "address": "House no: 15 & 16, Rd No 113/A, Dhaka 1212",
    "description":
        "Shahabuddin Medical College Hospital & Medical checkup unit provides a wide range of medical services with 500 bedded a multi-disciplinary super-specialty tertiary care hospital in Gulshan-2, Dhaka, and confidently providing comprehensive health care with the latest medical, surgical facilities including Medical checkup unit, diagnostics and consultation facilities. These services are provided by expert medical professionals, skilled nurses and technologists using latest technology.",
  },
  {
    "name": "Pancare Hospital Ltd.",
    "type": "Children's hospital in Dhaka",
    "rating": 4.0,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "01844-001024",
    "hours": "Open 24 Hours",
    "address": "Rd No. 27, Dhaka 1205",
    "description":
        "A private hospital with good service. Affordable for most people. Good for new born and child care. Intensive care service available for childrens here. Quality service for neonate and children are also maintained here. ",
  },
  {
    "name": "Paedihope Hospital For Sick Children",
    "type": "Children's hospital in Dhaka",
    "rating": 3.0,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "02-9671345",
    "hours": "Open 24 Hours",
    "address": "House- 32A, Road- 6, Dhanmondi, Dhaka 1205",
    "description":
        "A private hospital with good service. Affordable for most people.",
  },
  {
    "name": "Prime Bank Eye Hospital",
    "type": "Eye hospital in Dhaka",
    "rating": 4.0,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "02-9125530",
    "hours": "Open 24 Hours",
    "address":
        "House # 82, Road No. 8A(New), Satmosjid Road, Dhanmondi, Dhaka 1209",
    "description":
        "We give good service. Besides we offer good medical services within reasonable costs.",
  },
  {
    "name": "Usha Clinic",
    "type": "Psychiatric hospital in Dhaka",
    "rating": 5.0,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "01556-601494",
    "hours": "Everyday(10 AM-12 AM)",
    "address": "2/1, Kalabagan, Mirpur Road, Opp Dhanmondi Math, Dhaka 1205",
    "description":
        "We give good service. Besides we offer good medical services within reasonable costs.",
  },
  {
    "name": "LABAID Specialized Hospital",
    "type": "Specialized hospital in Dhaka",
    "rating": 4.0,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "09666-710606",
    "hours": "Open 24 Hours",
    "address": "House- -1 and, 6 Road No 4, Dhaka 1205",
    "description":
        "Labaid Hospital - the fist international standard super-specialty hospital of the country, dedicated exclusively to the diagnosis and treatment of cardiovascular diseases have been built on a six storied building at, Dhanmondi - a commercial cum residential hub of Dhaka City, covering a floor space of more than 100000 sq. feet.",
  },
  {
    "name": "City Hospital & Diagnostic Center",
    "type": "Private hospital in Dhaka",
    "rating": 3.5,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "02-8143312",
    "hours": "Open 24 Hours",
    "address": "House No#1, 8 Satmasjid Road, Dhaka 1207",
    "description":
        "We have different specialties like Medicine, Diabetes & Endocrinology, Gynaecology & Obstetrics, Neo-natology & Paediatric, Nephrology, Urology, ENT, Gastroenterology, General and Laparoscopic surgery, Oncology,Haemato-oncology, Neuro-medicine, Orthopaedic, Spine & Arthroscopic Surgery, Dermatology, Dental Surgery & Dental Implant and Physiotherapy.",
  },
  {
    "name": "Ibrahim General Hospital",
    "type": "General hospital in Dhaka",
    "rating": 4.5,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": " ",
    "hours": "Open 24 Hours",
    "address": "House-42,Rd-10/A, Dhaka 1205",
    "description":
        "Ibrahim General Hospital and The National Healthcare Network An Enterprise of Diabetic Association of Bangladesh, (former National Diagnostic Network (NDN). Basically it’s specialized for diabetic and relates with other syndrome diseases. It’s a systematic hospital and for new people it’ll be very tough to acquire process of treatments.",
  },
  {
    "name": "Popular Diagnostic Centre Ltd",
    "type": "Diagnostic center in Dhaka",
    "rating": 3.5,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "09613-787801",
    "hours": "Everyday(7 AM-11 PM)",
    "address": "HOUSE # 16 Rd No. 2, Dhaka 1205",
    "description":
        "Popular Diagnostic Centre Ltd. is an advanced Centre for diagnostic and medical services. It is one of the prestigious diagnostic complexes of Bangladesh which started its activities in 1983.",
  },
  {
    "name": "Medinova Medical Services Ltd.",
    "type": "Medical clinic in Dhaka",
    "rating": 4.0,
    "isfavourite": true,
    "image": "assets/host.png",
    "phone": "01750-557722",
    "hours": "Open 24 Hours",
    "address": "House 71/A, Road 5/A, Dhanmondi R/A, Dhaka 1209",
    "description":
        "We the MEDINOVA MEDICAL SERVICES LTD. an approved Medical Check-Up Center of the Executive Board of The Health Minister’s Council for G.C.C (Gulf Co-operation Council) States, bearing G.C.C Computer Code No. 05/01/24. We are one of the member medical centre under GAMCA, Dhaka-Bangladesh.",
  },
];
